//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Client
    {
        public Client()
        {
            this.Bookings = new HashSet<Booking>();
            this.Tokens = new HashSet<Token>();
        }
    
        public int clientid { get; set; }
        [Required]
        [EmailAddress]
        public string clientemail { get; set; }
        [Required]
        [StringLength(8)]
        public string password { get; set; }
        [Required]
        public string clientname { get; set; }
        [Required]
        [StringLength(11)]
        public string clientcontact { get; set; }
        [Required]
        public string username { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<Token> Tokens { get; set; }
    }
}
