//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public Package()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int packageid { get; set; }
        public string packagetype { get; set; }
        public string packagelocation { get; set; }
        public System.DateTime eventtime { get; set; }
        public string packageprice { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
